-- Esquema de base de datos para Diverxia Events
-- Ejecuta este script en el SQL Editor de tu nuevo proyecto de Supabase

-- Limpieza previa si las tablas ya existen
DROP TABLE IF EXISTS public.puntuaciones CASCADE;
DROP TABLE IF EXISTS public.pruebas CASCADE;
DROP TABLE IF EXISTS public.equipos CASCADE;
DROP TABLE IF EXISTS public.eventos CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;

-- Habilitar extensión UUID si no está habilitada
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Tabla de Usuarios (almacena el rol y nombre de cada usuario/juez)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY,
    nombre TEXT NOT NULL,
    rol TEXT NOT NULL CHECK (rol IN ('admin', 'juez', 'participante')),
    equipo_id UUID REFERENCES public.equipos(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS) o desactivarla según tu configuración original.
-- Para que funcione igual que antes de forma sencilla sin políticas restrictivas, puedes desactivar RLS en esta tabla o dejarla abierta:
ALTER TABLE public.usuarios DISABLE ROW LEVEL SECURITY;

-- 2. Tabla de Eventos
CREATE TABLE IF NOT EXISTS public.eventos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    descripcion TEXT,
    fecha DATE NOT NULL,
    fecha_fin DATE,
    estado TEXT DEFAULT 'abierto' NOT NULL CHECK (estado IN ('abierto', 'cerrado', 'finalizado')),
    display_order INTEGER DEFAULT 0 NOT NULL,
    num_jueces INTEGER DEFAULT 5 NOT NULL CHECK (num_jueces >= 1 AND num_jueces <= 10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.eventos DISABLE ROW LEVEL SECURITY;

-- 3. Tabla de Pruebas
CREATE TABLE IF NOT EXISTS public.pruebas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    evento_id UUID REFERENCES public.eventos(id) ON DELETE CASCADE NOT NULL,
    nombre TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.pruebas DISABLE ROW LEVEL SECURITY;

-- 4. Tabla de Equipos
CREATE TABLE IF NOT EXISTS public.equipos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    evento_id UUID REFERENCES public.eventos(id) ON DELETE CASCADE NOT NULL,
    nombre TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.equipos DISABLE ROW LEVEL SECURITY;

-- 5. Tabla de Puntuaciones
CREATE TABLE IF NOT EXISTS public.puntuaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id UUID REFERENCES public.equipos(id) ON DELETE CASCADE, -- Nullable para permitir bloquear pruebas
    prueba_id UUID REFERENCES public.pruebas(id) ON DELETE CASCADE NOT NULL,
    de_usuario UUID REFERENCES public.usuarios(id) ON DELETE CASCADE NOT NULL,
    valor INTEGER NOT NULL CHECK (valor >= 0 AND valor <= 1000),
    tipo TEXT, -- Ej: 'juez' o null
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.puntuaciones DISABLE ROW LEVEL SECURITY;

-- 6. Insertar Jueces predeterminados con UUIDs estáticos para separar sus votos
INSERT INTO public.usuarios (id, nombre, rol) VALUES 
('00000000-0000-0000-0000-000000000001', 'Juez 1', 'juez'),
('00000000-0000-0000-0000-000000000002', 'Juez 2', 'juez'),
('00000000-0000-0000-0000-000000000003', 'Juez 3', 'juez'),
('00000000-0000-0000-0000-000000000004', 'Juez 4', 'juez'),
('00000000-0000-0000-0000-000000000005', 'Juez 5', 'juez'),
('00000000-0000-0000-0000-000000000006', 'Juez 6', 'juez'),
('00000000-0000-0000-0000-000000000007', 'Juez 7', 'juez'),
('00000000-0000-0000-0000-000000000008', 'Juez 8', 'juez'),
('00000000-0000-0000-0000-000000000009', 'Juez 9', 'juez'),
('00000000-0000-0000-0000-000000000010', 'Juez 10', 'juez')
ON CONFLICT (id) DO NOTHING;
